Add Starksheet, Kakarot and Kakasheet to the stack
keep-starknet-strange/madara-infra pull request #16
Opened 2023-07-26 14:14 UTC by ClementWalter

# Add Starksheet, Kakarot, Kakasheet and Madara swap

Also removed the unused misc-apps

2023-07-26 14:20 UTC, d-roak commented
I'm finishing the healthcheck directly on Dockerfile, let's merge this one after. Any reason to remove completely misc-apps? I would like to keep madara-swap and kakarot deployment scripts while we don't have an alternative

2023-07-26 18:27 UTC, ClementWalter commented
> I'm finishing the healthcheck directly on Dockerfile, let's merge this one after. Any reason to remove completely misc-apps? I would like to keep madara-swap and kakarot deployment scripts while we don't have an alternative

I've updated the PR with the full kakarot stack (contract + RPC)

I can add a madara-swap deployment as well with the same strategy (build a deployer image in the madara-swap repo and just use it here). I don't think that these misc-apps (that I did) were a good strategy

2023-07-26 18:29 UTC, ClementWalter commented
lol now that I've put kakarot RPC, I could also add kakasheet (starksheet evm in kakarot)

2023-07-26 21:02 UTC, d-roak requested changes

2023-07-26 21:02 UTC, d-roak commented on starknet-stack/docker-compose.yml
> +    platform: linux/x86_64
this requires an emulated environment in some devices. Can we have an alternative?

2023-07-26 22:15 UTC, d-roak commented on starknet-stack/docker-compose.yml
> +    platform: linux/x86_64
that image is also not on a registry nor being built

2023-07-27 06:35 UTC, ClementWalter commented on starknet-stack/docker-compose.yml
> +    healthcheck:
Actually I tried but it still doesn't work, see corresponding `docker compose ps` commands
- without

```
docker compose ps
NAME                      IMAGE                                         COMMAND                  SERVICE             CREATED             STATUS              PORTS
starknet-stack-madara-1   ghcr.io/keep-starknet-strange/madara:latest   "/madara-bin --rpc-e…"   madara              38 seconds ago      Up 38 seconds       0.0.0.0:9615->9615/tcp, 0.0.0.0:9944->9944/tcp, 0.0.0.0:30333->30333/tcp
```

- with
```
docker compose ps
NAME                                IMAGE                                         COMMAND                  SERVICE             CREATED             STATUS                   PORTS
starknet-stack-kakarot-deployer-1   ghcr.io/kkrt-labs/kakarot/deployer:latest     "python scripts/depl…"   kakarot-deployer    7 seconds ago       Up Less than a second    
starknet-stack-madara-1             ghcr.io/keep-starknet-strange/madara:latest   "/madara-bin --rpc-e…"   madara              7 seconds ago       Up 6 seconds (healthy)   0.0.0.0:9615->9615/tcp, 0.0.0.0:9944->9944/tcp, 0.0.0.0:30333->30333/tcp
```

2023-07-27 06:36 UTC, ClementWalter commented on starknet-stack/docker-compose.yml
> +    healthcheck:
I just pulled latest, and this makes me use image `sha256:be68c3bfe68a696571bf9b41287b0f8e8f003a9a7cfe6a05da2382a39a3c1c97`

2023-07-27 06:37 UTC, ClementWalter commented on starknet-stack/docker-compose.yml
> +    platform: linux/x86_64
sorry this is a mistake, forgot to update from another docker compose, the build image in ghcr is multi arch

2023-07-27 07:37 UTC, d-roak commented on starknet-stack/docker-compose.yml
> +    healthcheck:
let's try once this finishes: https://github.com/keep-starknet-strange/madara/actions/runs/5677451093

2023-07-27 10:17 UTC, d-roak approved these changes
가보자고

2023-07-27 10:17 UTC, merged